name: PR Review

on:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Review PR
        run: |
          # Perform automated checks (e.g., linting, testing)
          echo "Running automated checks..."
          # If checks pass, approve the PR
          echo "PR approved"
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"event\":\"APPROVE\"}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews
